site_name: Philia Space
site_description: pi pi pi philia
site_url: https://philiaspace.my.id
site_author: ryusuke  
nav:
  - Beranda: 'index.md'
  - 'Panduan':
         - 'Panduan Bahasa Jepang': 'panduan.md'
         - 'Panduan Ringkas Bahasa Jepang': 'panduan-ringkas-JP.md'
         - '30 Hari Awal': 'rutinitas-awal.md'
    #    - 'speaking.md'
    #    - 'animejp.md'
         - 'Belajar Kanji': 'kanji.md'
    #    - 'readingtips.md'
    #    - 'monolingual.md'
    #    - 'faq.md'
         - 'Perbaiki Font': 'font.md'
    #    - 'How to use 5ch': '2ch.md'
    #  - 'Visual Novels':
    #    - 'Learning Japanese with VNs': 'vn.md'
    #    - 'Visual Novel Setup': 'vn-setup.md'
  - 'LazyGuide - Mining':
      - 'Pengantar - LazyGuide': 'setup.md'
      - 'Setup Utama - LazyGuide':
        - 'Anki PC': 'setup-anki-pc-lazy-guide.md'
    #   - 'Yomitan PC (Yaaacha)': 'setup-yomitan-pc.md'
        - 'Yomitan PC': 'setup-yomitan-pc-lazy-guide.md'
        - 'Yomitan Android': 'setup-yomitan-android-lazy-guide.md'
        - 'ShareX (Windows)': 'setup-ShareX-pc.md'
    #   - 'Suwayomi PC': 'setup-suwayomi-pc.md'
    #   - 'OCR (MacOS)': 'setup-ocr-macos.md'
      - 'Setup PC - LazyGuide':
        - 'Anime': 'setup-anime-pc-lazy-guide.md'
        - 'LN & Buku': 'setup-LN-pc-lazy-guide.md'
        - 'Manga': 'setup-manga-pc-lazy-guide.md'
      - 'Setup Android - LazyGuide':
        - 'Anime': 'setup-anime-android-lazy-guide.md'
        - 'LN & Buku': 'setup-LN-android-lazy-guide.md'
        - 'Manga': 'setup-manga-android-lazy-guide.md'
      - 'Setup Lain':
        - 'Memperbarui Format Lapis': 'pembaruan-format-lapis.md'
    #   - 'Mangatan PC': 'setup-mangatan-pc.md'
    #   - 'Mangatan Android': 'setup-mangatan-android.md'
    #  - 'Resources':
    #    - 'Resources': 'resources.md' 
  - 'Lain-lain':
    # - 'Tentang Retention': 'tentang-retention.md'
      - 'Riwayat Perubahan': 'riwayat-perubahan.md'
      - 'Donate': 'donate.md'
theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: fff7c4
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: c9c189
      accent: cyan 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  custom_dir: overrides
  favicon: img/favicon.png
  logo: img/moe.svg
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/phi-li-a/philiaspace.my.id
repo_name: GitHub

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/lang.js
plugins:
  - search:
      lang:
        - id
        - ja
  - open-in-new-tab
# extra:
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: Français
#       link: /fr/
#       lang: fr
#     - name: Deutsch
#       link: /de/
#       lang: de
#     - name: Español
#       link: /es/
#       lang: es
#     - name: Italiano
#       link: /it/
#       lang: it
#     - name: Português (Brasil)
#       link: /pt-BR/
#       lang: pt-br
#     - name: Русский
#       link: /ru/
#       lang: ru
#     - name: tiếng Việt
#       link: /viet/
#       lang: viet
